// Runs BEFORE the controller. The client now only sends `language` and
// `sourceCode` — score/summary/issues/etc. are generated by the AI
// service, not supplied by whoever calls the API (see Phase 11).
function validateReview(req, res, next) {
  const { language, sourceCode } = req.body;

  const errors = [];

  if (!language || typeof language !== 'string') {
    errors.push('language is required and must be a string.');
  }

  if (!sourceCode || typeof sourceCode !== 'string') {
    errors.push('sourceCode is required and must be a string.');
  }

  if (errors.length > 0) {
    return res.status(400).json({ success: false, message: errors.join(' ') });
  }

  next();
}

module.exports = validateReview;
